OZ-Coding-School/oz_01_main-004-BE

- config/local.py
로컬 데이터 베이스 sqlite3 사용
> ### Title
> Conf: local db sqlite3 설정
> ### PR Type
>
> - [x] CONF: 빌드, 환경 설정
>
>
> Conf: local db sqlite3 설정

- config/base.py
> ### Title
> Conf: custom user apps 추가
> ### PR Type
>
> - [x] CONF: 빌드, 환경 설정
> 개발시 생성한 app 추가하는 custom user apps 추가
>
> Conf: custom user apps 추가

- .gitignore
> ### Title
> Remove: sqlite3.db 삭제
> ### PR Type
>
> - [x] REMOVE: 파일 삭제하는 작업만 수행한 경우
>
>
> Remove: sqlite3.db 삭제

- chat/admin.py
- chat/apps.py
- chat/consumers.py
- chat/models.py
- chat/routing.py
- chat/serializers.py
- chat/urls.py
- chat/views.py
- common/apps.py
- config/asgi.py
- config/base.py
- config/local.py
- config/prod.py
- config/routing.py
- config/urls.py
- config/wsgi.py
- manage.py
- poetry.lock
- pyproject.toml
> ### Title
>
> - Feat : chat app에 예외처리 및 consumers.py 수정
> ### PR Type
>
>
> - 채팅 기능에 예외처리 추가하고,
> 채팅API로 Websocket이 작동할수 있도록 작성해봄.
> 다음 버전에선 기능의 동작여부를 확인해서 수정하겟음.
> - ChatmessageFile 모델을 ChatFile로 수정했습니다.
> - black 을 이용해서 코드를 보기 좋게 수정했습니다. 
> 그래서 알림이 많을것 같습니다. 고의는 아닙니다. 죄송합니다.
>
> - consumers.py를 API로 데이터베이스에 데이터를 생성 한 후,
> 그 데이터를 웹소켓으로 채팅에 참가한 유저들에게 보내주는 형식으로 구현했습니다.
> 데이터 처리 속도가 원할하지 않는다면 자웅에 다시 수정하겠습니다.
> Feat : chat app에 예외처리 및 consumers.py 수정

- .dockerignore
- Dockerfile
- chat/admin.py
- chat/consumers.py
- chat/models.py
- chat/routing.py
- chat/serializers.py
- chat/urls.py
- chat/views.py
- config/asgi.py
- config/base.py
- config/local.py
- config/prod.py
- config/routing.py
- config/urls.py
- docker-compose.yml
- entrypoint.sh
- nginx/django.conf
- poetry.lock
- pyproject.toml
> ### Title
> Deploy: Docker 로 배포
> ### PR Type
>
> - [x] DEPLOY: 배포 관련
>
> Dockerfile 생성해서 docker-compose로 build, up 하여 실행
> nginx, gunicorn, django 를 docker 컨테이너에 넣음 settings.py 에 필요한 설정 추가
>
> Deploy: Docker 로 배포

- chat/models.py
- config/base.py
- config/urls.py
- users/admin.py
- users/apps.py
- users/models.py
- users/serializers.py
- users/tests.py
- users/urls.py
- users/views.py
> ### Title
> Feat : 사용자 회원가입 / 로그인 / 로그아웃 / 수정/조회/탈퇴
> ### PR Type
>
> - 사용자 CRUD / 로그인/로그아웃 기능구현 완료
> - 토큰 발급 및 리프레쉬 토큰 이용하여 액세스토큰 재발급
>
> Feat : 사용자 회원가입 / 로그인 / 로그아웃 / 수정/조회/탈퇴

- users/serializers.py
- users/urls.py
- users/views.py
> ### Title
> Feat: 유저 프로필 이미지 업로드 기능 구현
> ### PR Type
>
> - 로그인한 유저의 프로필 이미지 S3 에 업로드 후
> - 해당 프로필 이미지의 url 주소를 db 에 저장
>
> Feat: 유저 프로필 이미지 업로드 기능 구현

- chat/urls.py
- comments/admin.py
- comments/apps.py
- comments/models.py
- comments/tests.py
- comments/views.py
- favorite/admin.py
- favorite/apps.py
- favorite/models.py
- favorite/tests.py
- favorite/views.py
- foods/admin.py
- foods/apps.py
- foods/models.py
- foods/tests.py
- foods/views.py
- recipes/admin.py
- recipes/apps.py
- recipes/models.py
- recipes/tests.py
- recipes/views.py
- users/serializers.py
- users/urls.py
- users/views.py
> ### Title
> - Feat: recipes, foods, favorite, commetns 앱 생성
> - Refactor: urls.py 에서 끝에 '/' 제거  
> ### PR Type
>
>
>
> Feat: recipes, foods, favorite, commetns 앱 생성

- config/base.py
- users/serializers.py
- users/urls.py
- users/views.py
> ### Title
> - Fix: api endpoint url '/' 추가, 유저 업데이트 serializer 추가 후 변경
> ### PR Type
>
> - 카카오 로그인 기능 구현 해놓고
유저 업데이트시 기존 serializer 와 분리해 serializer 따로 빼서 사용
> - 코드 스타일 black, isrot 사용
>
> Feat: Kakao 로그인 기능 구현

- users/urls.py
> ### Title
>
> - Fix: kakao login url 추가 안되어 있던거 수정
> ### PR Type
>
> - urls.py 에 kakao login api endpoint 설정 안되어있어서 404 에러 뜨는거 수정
>
> Fix: kakao login url 추가 안되어 있던거 수정

- chat/urls.py
- config/base.py
- config/urls.py
- foods/admin.py
- foods/models.py
- foods/serializers.py
- foods/urls.py
- foods/views.py
> ### Title
> - Feat: 음식 종류/재료 별 카테고리 값 저장 및 조회 기능 구현
> ### PR Type
>
> - FoodType, FoodIngredient 어드민 페이지에서 값 저장하고
각 이미지의 S3 주소와 카테고리 정보 조회
>
> Feat: 음식 종류/재료 별 카테고리 값 저장 및 조회 기능 구현

- config/base.py
> ### Title
> - Fix: access, refresh 토큰 life time 설정
> ### PR Type
>
>
>
> Fix: access, refresh 토큰 life time 설정

- users/views.py
> ### Title
>
> - Fix: 로그아웃시 access token 필요X
> ### PR Type
>
>
> - 로그아웃 시에 access token 없어도 로그아웃 가능하게 설정 변경
>
> Fix: 로그아웃시 access token 필요X

- chat/serializers.py
채팅방 생성안되던 버그 해결
> ### Title
>
> - Fix : 채팅방 생덩안된던 버그 수정
> ### PR Type
>
>
> - 채팅방 생성안되던 버그 해결
> - 좋습니다 👍
>
> Fix : 채팅방 생덩안된던 버그 수정

- chat/routing.py
- chat/views.py
- config/asgi.py
- config/routing.py
- favorite/models.py
라우팅 설정을 변경했습니다.
> ### Title
>
> - Refactor : chatting routing 설정 변경
> ### PR Type
>
>
> - 라우팅 설정을 변경했습니다.
> - 깜박하고 브랜치 안바꿨습니다. 이번거 PR하면 변경해서 작업하겠습니다.👍
>
> Refactor : chatting routing 설정 변경

- chat/models.py
- chat/serializers.py
- chat/views.py
채팅방 전채 불러오기 수정했고,
메시지모델과 파일모델에 이름을 붙여줘서
models가 수정됨
> ### Title
>
> - 제목은 'Feat: 홈 페이지 구현'과 같이 작성합니다.
> ### PR Type
>
>
> - 채팅방 전채 불러오기 수정했고,
> 메시지모델과 파일모델에 이름을 붙여줘서
> models가 수정됨
> - 진짜 미안쓰 다음엔 꼭 브랜치 삭제하고 다른이음으로 만들겠음
>
> - 다음번에도 브랜치 변경 안하면 욕해주기
> - 웹소켓도 CORS설정 해줘야 한다고 합니다. 같이 설정해 봐요
>  Feat : 채링방 전체불러오기 수정

- docker-compose.yml
- entrypoint.sh
- nginx/django.conf
> ### Title
>
> - Deploy: 서버 배포후 websocket daphne 연결 설정
> ### PR Type
>
> - [x] DEPLOY: 배포 관련
>
> - nginx 설정파일 수정 및 docker-compose.yml , entrypoint.sh 파일 수정
>
> Deploy: 서버 배포후 websocket daphne 연결 설정

- users/serializers.py
- users/urls.py
> ### Title
>
> - Fix: profile image 작동 오류 해결 및 users/serializers.py 수정
> ### PR Type
>
>
> - urls.py 에 있는 프롤필 이미지 url 수정 및
serializers.py 에 있는 토큰 발급로직에서 유저 정보 포함을 위한 유저 정보 db 에서 불러오는 코드 추가
>
> Fix: profile image 작동 오류 해결 및 users/serializers.py 수정

- comments/admin.py
- comments/models.py
- config/base.py
- config/urls.py
- favorite/admin.py
- favorite/models.py
- foods/models.py
- foods/serializers.py
- recipes/admin.py
- recipes/models.py
- recipes/serializers.py
- recipes/urls.py
- recipes/views.py
> ### Title
>
> - Feat: Rcipe CRUD 기능 구현
> ### PR Type
>
>
> - Recipe CRUD 기능 구현 및 comments, favorite 앱 models.py, admin.py 수정 및 마이그레이션
>
> Feat: Rcipe CRUD 기능 구현

- comments/urls.py
- comments/views.py
> ### Title
>
> Fix: comments url update
> ### PR Type
>
>
> 겹치는 api 업데이트
url 수정
>
> Fix: comments url update

- config/prod.py
- config/urls.py
- favorite/models.py
- favorite/serializers.py
- favorite/urls.py
- favorite/views.py
- foods/views.py
- recipes/models.py
- recipes/serializers.py
- recipes/urls.py
- recipes/views.py
> ### Title
>
> - Feat: Favoite 찜 기능 추가 및 Recipe 조회시 찜 여부 표시, 마이페이지에서 내가작성한 Recipe 목록 조회기능 구현
> ### PR Type
>
>
> - 찜 목록 조회 및 찜하기 취소하기 기능 구현
> - 로그인 한 경우 전체게시글 및 메인 페이지 게시글에 찜한 게시글 표시를 위해 is_favorite 변수 true, false로 데이터 내려주는 기능 추가
> - 자신의 게시물 또는 두번 찜하지 못하도록 예외 처리
> - 마이페이지에서 내가작성한 Reciep 목록 조회기능 구현
>
> Feat: Favoite 찜 기능 추가 및 Recipe 조회시 찜 여부 표시, 마이페이지에서 내가작성한 Recipe 목록 조회기능 구현

- entrypoint.sh
> ### Title
>
> - Fix: entrypoint.sh 수정
> ### PR Type
>
>
> - entrypoint.sh 내의 migrations 명령 주석처리
>
> Fix: entrypoint.sh 수정

- users/views.py
> ### Title
> Fix: UserProfileImageView 이미지 형식/크기 관련 예외처리
> ### PR Type
>
> 이미지 형식과 크기에 대한 검증 기능을 추가
>
> Fix: UserProfileImageView 이미지 형식/크기 관련 예외처리

- recipes/views.py
> ### Title
>
> - Fix: 내가작성한 Recipe 리스트 조회시 버그 수정
> ### PR Type
>
>
> - 구체적인 작업 내용을 작성해주세요.
> - 이미지를 별도로 첨부하면 더 좋습니다 👍
>
> Fix: 내가작성한 Recipe 리스트 조회시 버그 수정

- chat/consumers.py
connect의 room_name을 room_id로 수정
> ### Title
>
> - Refactor  : consumers 수정
> ### PR Type
>
>
> - connect의 room_name을 room_id로 수정
> -  👍
>
>  Refactor  : consumers 수정

- favorite/views.py
- recipes/serializers.py
- recipes/views.py
> ### Title
>
> - Fix: 내가 찜한 Recipe 목록 조회 기능 수정 및 Recipe content 이미지 업로드 기능 수정
> ### PR Type
>
>
> -  👍
>
> - 👍
> Fix: 내가 찜한 Recipe 목록 조회 기능 수정 및 Recipe content 이미지 업로드 기능 수정

- comments/serializers.py
- comments/views.py
- favorite/serializers.py
- foods/views.py
> ### Title
>
> - Fix: 댓글 생성 기능 수정및 유저정보 표시
> ### PR Type
>
>
> - 댓글 생성 기능시 400 error 수정 및 유저정보도 함께 응답
> - 찜한 게시글 목록 조회시 버그 수정 및 food_ingredient pagination warning 수정
>
> Fix: 댓글 생성 기능 수정및 유저정보 표시

- recipes/models.py
- recipes/serializers.py
- recipes/urls.py
- recipes/views.py
> ### Title
>
> - Fix: recipe image 업로드 기능 수정
> ### PR Type
>
>
> - recipe 이미지 업로드시 recipe_id 제거
>
> Fix: recipe image 업로드 기능 수정

- favorite/urls.py
- favorite/views.py
> ### Title
>
> - Fix: favorite 삭제시 Recipe id, User id 로 검색 후 삭제
> ### PR Type
>
>
> - 찜 생성 url 변경 및 삭제시 Recipe id , User id 값으로 삭제
>
> Fix: favorite 삭제시 Recipe id, User id 로 검색 후 삭제

- chat/admin.py
- chat/consumers.py
- chat/models.py
- chat/serializers.py
- chat/views.py
- config/base.py
- config/local.py
> ### Title
>
> - Refactor  : 컨슈머 동작 변경함
> ### PR Type
>
>
> - 컨슈머 동작 변경했는데 read_by 필드가 어떻게 동작하는지 봐야 다른거 할수있어서,
> - 우선 커밋함 👍
>
> Refactor  : 컨슈머 동작 변경함

- chat/consumers.py
- chat/views.py
- config/base.py
> ### Title
>
> - Fix : 메세지 전송안되는 버그 수정
> ### PR Type
>
>
> - 메세지 전송할떄 타입을 정해 줘야 하고,
> - 메시지 생성 엔드포인트에 인즈 기능 우선 주석처리 함 👍
>
> Fix : 메세지 전송안되는 버그 수정

- favorite/views.py
- recipes/views.py
> ### Title
>
> - Fix: 페이지네이션 버그 수정
> ### PR Type
>
>
> - 구체적인 작업 내용을 작성해주세요.
> - 이미지를 별도로 첨부하면 더 좋습니다 👍
>
> Fix: 페이지네이션 버그 수정

- chat/consumers.py
- config/base.py
- config/urls.py
> ### Title
>
> - Refactor  : config.urls 수정함
> ### PR Type
>
>
> - 포트 문제인거 같아서 엔드포인트를 수정함
> -  👍
>
> Refactor  : config.urls 수정함

- comments/views.py
- favorite/views.py
- recipes/views.py
- users/views.py
> ### Title
>
> - Fix: 게시글 생성시 게시글 데이터 정보 내려주는 기능
> - Refactor: 코드 간결하게 수정
> ### PR Type
>
> 
>
> Fix: 게시글 생성시 게시글 데이터 정보 내려주는 기능

- chat/consumers.py
- config/base.py
- config/local.py
> ### Title
>
> - Fix  : 서버에서 돌아가게 수정함
> ### PR Type
>
>
> - ssl이 있어서 리디렉션이 되면 어떻게 될지는 모르겠는데
> - 우선은 서버 자체 요청시에는 localhost와 포트를 입력하면 되네요. 👍
>
>  Fix  : 서버에서 돌아가게 수정함

- chat/views.py
> ### Title
>
> -  Style  : 페이지네이션 사이즈 변경, 메세지 생성시 예외처리 제거
> ### PR Type
>
> - [x] STYLE: 스타일 (코드 형식, 세미콜론 추가: 비즈니스 로직에 변경 없음)
>
> - 페이지네이션 사이즈를 10개씩으로 증가함
> - 메시지 생성시 예외처리 부분 우선 주석처리 👍
>
>  Style  : 페이지네이션 사이즈 변경, 메세지 생성시 예외처리 제거

- recipes/models.py
- recipes/serializers.py
- recipes/views.py
> ### Title
>
> - Fix: recipe content 이미지 저장시 uuid 설정
> ### PR Type
>
>
> - recipe id 가 생성되기 전에 image를 생성하기 때문에 image 식별을 위해 uuid field 추가
>
> Fix: recipe content 이미지 저장시 uuid 설정

- config/prod.py
- recipes/views.py
> ### Title
>
> - Fix: uuid_list 리스트 접근 방법 수정
> ### PR Type
>
>
>
> Fix: uuid_list 리스트 접근 방법 수정

- recipes/views.py
> ### Title
>
> - Fix: image upload 시에 uuid 값 받아 처리
> ### PR Type
>
>
> - image upload 시에 해당 recipe 게시물에 속한 image 들을 연결 하기위해 uuid 값 받아 처리 하는 로직 구현
>
> Fix: image upload 시에 uuid 값 받아 처리

- recipes/views.py
> ### Title
>
> - Fix: image upload 수정
> ### PR Type
>
>
> - image upload 시 uuid 값 받아서 처리하는 부분 수정
>
> Fix: image upload 수정

- recipes/views.py
> ### Title
>
> - Fix: recipe content image upload 수정
> ### PR Type
>
>
> - recipe content 에서 image upload 시 uuid 값 받아 올 때 에러 수정
>
> Fix: recipe content image upload 수정

- comments/serializers.py
- comments/views.py
> ### Title
>
> - Fix: 댓글 생성시 데이터 응답 및 유저정보 표시
> ### PR Type
>
>
> - 댓글 생성시 생성된 댓글 데이터 응답
> - 댓글 데이터에 유저정보 표시
>
> Fix: 댓글 생성시 데이터 응답 및 유저정보 표시

- recipes/views.py
> ### Title
>
> - Feat: recipe image 수정 기능 구현
> ### PR Type
>
>
> - recipe 이미지 수정시 s3 및 db 데이터 업데이트
>
> Feat: recipe image 수정 기능 구현

- docker-compose.yml
- favorite/views.py
- nginx/django.conf
- recipes/views.py
- users/serializers.py
> ### Title
>
> - Fix: nginx, docker-compose.yml 파일 수정
> ### PR Type
>
>
> - daphne 로 서버 오픈 설정
>
> Fix: nginx, docker-compose.yml 파일 수정

- chat/consumers.py
- config/base.py
> ### Title
>
> - Deploy  : 컨슈머 베이스 수정
> ### PR Type
>
>
> - 컨슈머랑 베이스 수정
>
> Deploy  : 컨슈머 베이스 수정

- chat/consumers.py
> ### Title
>
> - Refactor  : 엔드포인트 호출 변경
> ### PR Type
>
>
> - 엔드포인트 호출 변경
>
> Refactor  : 엔드포인트 호출 변경

- README.md
> ### Title
>
> - Docs: Read Me 문서 추가
> ### PR Type
>
> - [x] DOCS: 문서 추가 및 수정
>
> - Read Me 문서 추가
>
> Docs: Read Me 문서 추가

- config/base.py
- config/prod.py
- nginx/django.conf
> ### Title
>
> - Fix: config/prod, config/base, nginx/django.conf 파일수정
> ### PR Type
>
>
> - jwt access token 시간 조정 및 nignx 라우팅 수정
> - 프론트 배포 페이지 cors, csrf 허용
>
> Fix: config/prod, config/base, nginx/django.conf 파일수정

- favorite/serializers.py
> ### Title
>
> - Fix: favorite serializer 수정
> ### PR Type
>
>
> - favorite serializer 에서 user 정보 내려주는걸로 수정
>
> Fix: favorite serializer 수정

- users/urls.py
- users/views.py
> ### Title
>
> - Fix: token refresh 수정
> ### PR Type
>
>
> - token refresh 제대로 발급 받았는데도 불구하고 401 에러 뜨는거
수정 테스트
>
> Fix: token refresh 수정

- config/base.py
- users/urls.py
- users/views.py
> ### Title
>
> - Fix: access token expire time 수정  및 toekn refresh 수정
> ### PR Type
>
>
> - access token 기한 연장 및 token refresh 원래 코드로 복구
>
> Fix: access token expire time 수정  및 toekn refresh 수정

- README.md
> ### Title
>
> - Docs: Develop to Main
> ### PR Type
>
> - [x] DOCS: 문서 추가 및 수정
>
>
> Docs: Develop to Main

- recipes/views.py
> ### Title
>
> - Fix: recipe 검색시 작성자 nickname으로 검색 추가
> ### PR Type
>
>
> - recipe 검색시 기존 제목과 게시글 내용에서 검색 하는 기능 과 더불어
작성자의 nickname 도 검색하는 기능 추가
>
> Fix: recipe 검색시 작성자 nickname으로 검색 추가
